# Generated by Django 6.0.4 on 2026-05-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('attempts', models.IntegerField(default=0, verbose_name='عدد المحاولات')),
                ('lock_until', models.DateTimeField(blank=True, null=True, verbose_name='وقت انتهاء الحظر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'متابع رمز التحقق',
                'verbose_name_plural': 'متابعو رموز التحقق',
            },
        ),
    ]
