# Generated by Django 6.0.3 on 2026-04-17 02:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDBConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المصدر')),
                ('host', models.CharField(max_length=255, verbose_name='العنوان (Host)')),
                ('port', models.PositiveIntegerField(default=5432, verbose_name='المنفذ (Port)')),
                ('dbname', models.CharField(max_length=255, verbose_name='اسم قاعدة البيانات (Database Name)')),
                ('user', models.CharField(max_length=255, verbose_name='اسم المستخدم (User)')),
                ('password', models.CharField(max_length=255, verbose_name='كلمة المرور (Password)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=1440, editable=False, help_text='فترة المزامنة التلقائية (24 ساعة)', verbose_name='فترة المزامنة (دقائق)')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('connection_timeout', models.IntegerField(default=30, verbose_name='مهلة الاتصال (ثانية)')),
                ('max_connections', models.IntegerField(default=10, verbose_name='الحد الأقصى للاتصالات')),
                ('quick_schedule', models.CharField(choices=[('24hours', 'كل 24 ساعة')], default='24hours', editable=False, help_text='مزامنة تلقائية كل 24 ساعة', max_length=20, verbose_name='جدولة تلقائية')),
                ('sync_interval_type', models.CharField(choices=[('minutes', 'دقائق')], default='minutes', editable=False, max_length=20, verbose_name='نوع الفترة')),
                ('ssl_mode', models.CharField(choices=[('disable', 'معطل'), ('require', 'مطلوب'), ('prefer', 'مفضل'), ('verify-ca', 'تحقق من CA'), ('verify-full', 'تحقق كامل')], default='prefer', max_length=20, verbose_name='وضع SSL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_db_configs', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'إعداد قاعدة بيانات خارجية',
                'verbose_name_plural': 'إعدادات قواعد البيانات الخارجية',
                'db_table': 'ExternalDBConfigs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_table', models.CharField(blank=True, help_text='اسم الجدول في قاعدة البيانات الخارجية', max_length=255, null=True, verbose_name='الجدول الخارجي')),
                ('local_model', models.CharField(blank=True, help_text='اسم النموذج في Django', max_length=100, null=True, verbose_name='النموذج المحلي')),
                ('local_app', models.CharField(blank=True, help_text='اسم التطبيق في Django', max_length=50, null=True, verbose_name='التطبيق المحلي')),
                ('field_mappings', models.JSONField(blank=True, default=list, help_text='قائمة تعيينات الحقول بين الجدول الخارجي والنموذج المحلي', verbose_name='تعيينات الحقول')),
                ('sync_strategy', models.CharField(choices=[('full_sync', 'مزامنة كاملة'), ('batch_sync', 'مزامنة دفعية'), ('incremental_sync', 'مزامنة تزايدية'), ('create_new', 'إنشاء نموذج جديد')], default='full_sync', max_length=20, verbose_name='استراتيجية المزامنة')),
                ('confidence_score', models.FloatField(default=0.0, help_text='درجة الثقة في التعيين (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='درجة الثقة')),
                ('is_auto_discovered', models.BooleanField(default=False, help_text='هل تم اكتشاف هذا التعيين تلقائياً', verbose_name='مكتشف تلقائياً')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('source_field', models.CharField(blank=True, max_length=255, null=True, verbose_name='الحقل المصدر')),
                ('target_field', models.CharField(blank=True, max_length=255, null=True, verbose_name='الحقل الهدف')),
                ('target_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='النموذج الهدف')),
                ('field_type', models.CharField(blank=True, choices=[('string', 'نص'), ('integer', 'رقم صحيح'), ('float', 'رقم عشري'), ('boolean', 'منطقي'), ('date', 'تاريخ'), ('datetime', 'تاريخ ووقت'), ('json', 'JSON'), ('foreign_key', 'مفتاح خارجي'), ('binary', 'بيانات ثنائية'), ('image', 'صورة')], default='string', max_length=20, null=True, verbose_name='نوع الحقل')),
                ('is_required', models.BooleanField(default=False, verbose_name='مطلوب')),
                ('default_value', models.TextField(blank=True, null=True, verbose_name='القيمة الافتراضية')),
                ('transformation_rule', models.TextField(blank=True, null=True, verbose_name='قاعدة التحويل')),
                ('validation_rule', models.TextField(blank=True, null=True, verbose_name='قاعدة التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('db_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_data_mappings', to='data_sync.externaldbconfig', verbose_name='إعداد قاعدة بيانات')),
            ],
            options={
                'verbose_name': 'تعيين بيانات',
                'verbose_name_plural': 'تعيينات البيانات',
                'db_table': 'DataMappings',
                'ordering': ['-confidence_score', 'external_table', 'local_model'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(default='unknown', help_text='اسم مصدر البيانات للسجل', max_length=255, verbose_name='مصدر البيانات')),
                ('sync_type', models.CharField(choices=[('full', 'كامل'), ('incremental', 'تزايدي'), ('manual', 'يدوي'), ('scheduled', 'مجدول'), ('auto_discovery', 'اكتشاف تلقائي')], default='full', max_length=20, verbose_name='نوع المزامنة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('records_processed', models.PositiveIntegerField(default=0, verbose_name='عدد السجلات المعالجة')),
                ('records_updated', models.PositiveIntegerField(default=0, verbose_name='السجلات المحدثة')),
                ('records_failed', models.PositiveIntegerField(default=0, verbose_name='السجلات الفاشلة')),
                ('records_created', models.PositiveIntegerField(default=0, verbose_name='السجلات الجديدة')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='معلومات إضافية عن المزامنة مثل الجداول والتعيينات', verbose_name='بيانات وصفية')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='المدة بالثواني')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت البداية')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('db_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs_db', to='data_sync.externaldbconfig', verbose_name='إعداد قاعدة بيانات')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_syncs', to=settings.AUTH_USER_MODEL, verbose_name='أطلق بواسطة')),
            ],
            options={
                'verbose_name': 'سجل المزامنة',
                'verbose_name_plural': 'سجلات المزامنة',
                'db_table': 'SyncLogs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='externaldbconfig',
            index=models.Index(fields=['is_active'], name='ExternalDBC_is_acti_fb1f81_idx'),
        ),
        migrations.AddIndex(
            model_name='externaldbconfig',
            index=models.Index(fields=['last_sync'], name='ExternalDBC_last_sy_40e682_idx'),
        ),
        migrations.AddIndex(
            model_name='datamapping',
            index=models.Index(fields=['db_config', 'is_active'], name='DataMapping_db_conf_16bdf3_idx'),
        ),
        migrations.AddIndex(
            model_name='datamapping',
            index=models.Index(fields=['external_table'], name='DataMapping_externa_84ba01_idx'),
        ),
        migrations.AddIndex(
            model_name='datamapping',
            index=models.Index(fields=['local_model'], name='DataMapping_local_m_2bcdfc_idx'),
        ),
        migrations.AddIndex(
            model_name='datamapping',
            index=models.Index(fields=['confidence_score'], name='DataMapping_confide_81c747_idx'),
        ),
        migrations.AddIndex(
            model_name='datamapping',
            index=models.Index(fields=['is_auto_discovered'], name='DataMapping_is_auto_ef385c_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['db_config', 'started_at'], name='SyncLogs_db_conf_b346fa_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status'], name='SyncLogs_status_06680e_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['sync_type'], name='SyncLogs_sync_ty_70dc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['data_source'], name='SyncLogs_data_so_888671_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['started_at'], name='SyncLogs_started_246d71_idx'),
        ),
    ]
