# Generated by Django 6.0.3 on 2026-04-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISourceConfig',
            fields=[
            ],
            options={
                'verbose_name': 'إعداد الاتصال بـ API رسمي',
                'verbose_name_plural': 'إعدادات الاتصال بـ APIs الرسمية',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data_sync.externaldbconfig',),
        ),
        migrations.CreateModel(
            name='ScrapingSourceConfig',
            fields=[
            ],
            options={
                'verbose_name': 'إعداد عملية قشط مواقع',
                'verbose_name_plural': 'إعدادات عمليات قشط المواقع',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data_sync.externaldbconfig',),
        ),
        migrations.AlterField(
            model_name='externaldbconfig',
            name='dbname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم قاعدة البيانات (Database Name)'),
        ),
        migrations.AlterField(
            model_name='externaldbconfig',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='كلمة المرور (Password)'),
        ),
        migrations.AlterField(
            model_name='externaldbconfig',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المستخدم (User)'),
        ),
    ]
