# Generated by Django 6.0.3 on 2026-04-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync', '0002_apisourceconfig_scrapingsourceconfig_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapingSourceConfig',
        ),
    ]
