# Generated by Django 6.0.3 on 2026-04-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync', '0003_delete_scrapingsourceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldbconfig',
            name='test_vin',
            field=models.CharField(blank=True, help_text='رقم هيكل صالح لاستخدامه في الاكتشاف التلقائي للحقول', max_length=17, null=True, verbose_name='رقم هيكل تجريبي (Test VIN)'),
        ),
    ]
