# Generated by Django 6.0.3 on 2026-04-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync', '0004_externaldbconfig_test_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldbconfig',
            name='seed_vins',
            field=models.TextField(blank=True, help_text='أرقام هيكل مفصولة بفواصل أو أسطر جديدة. تُستخدم كبداية لمصادر API التي تتطلب VIN محدد (تحتوي على {vin}) عند عدم وجود بيانات محلية.', null=True, verbose_name='أرقام هيكل أولية (Seed VINs)'),
        ),
    ]
