# Generated by Django 6.0.3 on 2026-04-17 02:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('vin', models.CharField(db_column='VIN', max_length=17, primary_key=True, serialize=False, verbose_name='رقم الهيكل')),
                ('name_car', models.CharField(max_length=255, verbose_name='اسم السيارة')),
                ('make', models.CharField(max_length=100, verbose_name='الشركة المصنعة')),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='سنة الصنع')),
                ('color', models.CharField(max_length=50, verbose_name='اللون')),
                ('seating_capacity', models.IntegerField(blank=True, null=True, verbose_name='عدد المقاعد')),
                ('engine_size', models.CharField(max_length=50, verbose_name='حجم المحرك')),
                ('num_cylinders', models.IntegerField(blank=True, null=True, verbose_name='عدد الاسطوانات')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'بنزين'), ('diesel', 'ديزل'), ('electric', 'كهربائي'), ('hybrid', 'هجين'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الوقود')),
                ('engine_capacity', models.IntegerField(verbose_name='سعة المحرك (سم³)')),
                ('gear_type', models.IntegerField(choices=[(1, 'عادي'), (2, 'أوتوماتيك')], verbose_name='نوع ناقل الحركة')),
                ('customs_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم البيان الجمركي')),
                ('customs_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البيان الجمركي')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الإيصال')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإيصال')),
                ('mileage', models.IntegerField(default=0, verbose_name='المسافة المقطوعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'سيارة',
                'verbose_name_plural': 'السيارات',
                'db_table': 'Cars',
                'indexes': [models.Index(fields=['vin'], name='Cars_VIN_f3b87e_idx'), models.Index(fields=['make', 'model'], name='Cars_make_e3fa59_idx'), models.Index(fields=['year'], name='Cars_year_a4c0fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(choices=[('general', 'استفسار عام'), ('support', 'دعم فني'), ('complaint', 'شكوى'), ('suggestion', 'اقتراح أو ملاحظة'), ('other', 'أخرى')], default='general', max_length=50, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='رقم الهيكل')),
                ('urgent', models.BooleanField(default=False, verbose_name='عاجل')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة')),
                ('reference_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة اتصال',
                'verbose_name_plural': 'رسائل الاتصال',
                'db_table': 'ContactMessages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'created_at'], name='ContactMess_is_read_1e2ff2_idx'), models.Index(fields=['subject'], name='ContactMess_subject_43061a_idx'), models.Index(fields=['reference_number'], name='ContactMess_referen_10e0af_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccidentImage',
            fields=[
                ('accident_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('accident_image', models.BinaryField(blank=True, null=True, verbose_name='صورة الحادث (تخزين في قاعدة البيانات)')),
                ('ai_description', models.TextField(blank=True, null=True, verbose_name='الوصف التلقائي بالذكاء الاصطناعي')),
                ('ai_accident_type', models.CharField(blank=True, choices=[('front', 'اصطدام أمامي'), ('rear', 'اصطدام خلفي'), ('side', 'اصطدام جانبي'), ('rollover', 'انقلاب'), ('minor', 'حادث بسيط'), ('major', 'حادث كبير'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='نوع الحادث (تحليل الذكاء الاصطناعي)')),
                ('ai_analysis_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='بيانات تحليل الذكاء الاصطناعي')),
                ('ai_confidence_score', models.FloatField(blank=True, help_text='درجة ثقة الذكاء الاصطناعي في التحليل (0-1)', null=True, verbose_name='درجة ثقة التحليل')),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تحليل الذكاء الاصطناعي')),
                ('ai_analysis_enabled', models.BooleanField(default=True, verbose_name='تفعيل تحليل الذكاء الاصطناعي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident_images', to='cars.cars', verbose_name='السيارة')),
            ],
            options={
                'verbose_name': 'صورة حادث',
                'verbose_name_plural': 'صور الحوادث',
                'db_table': 'accident_images',
                'ordering': ['-accident_image_id'],
                'indexes': [models.Index(fields=['car'], name='accident_im_car_id_bcf2da_idx'), models.Index(fields=['ai_analyzed_at'], name='accident_im_ai_anal_709d99_idx'), models.Index(fields=['ai_confidence_score'], name='accident_im_ai_conf_4b6354_idx')],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluation_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='تعليق')),
                ('pros', models.TextField(blank=True, null=True, verbose_name='الإيجابيات')),
                ('cons', models.TextField(blank=True, null=True, verbose_name='السلبيات')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='هل يوصي بها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='cars.cars', verbose_name='السيارة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'teqyeem',
                'verbose_name_plural': 'alteqyeemat',
                'db_table': 'evaluation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['car', 'rate'], name='evaluation_car_id_372c7d_idx'), models.Index(fields=['user', 'created_at'], name='evaluation_user_id_a462df_idx')],
                'unique_together': {('car', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ImageCar',
            fields=[
                ('img_car_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_car', models.BinaryField(blank=True, null=True, verbose_name='صورة السيارة (تخزين في قاعدة البيانات)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.cars', verbose_name='السيارة')),
            ],
            options={
                'verbose_name': 'صورة سيارة',
                'verbose_name_plural': 'صور السيارات',
                'db_table': 'image_car',
                'ordering': ['-img_car_id'],
                'indexes': [models.Index(fields=['car'], name='image_car_car_id_e5eb0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Repairshops',
            fields=[
                ('repairshop_id', models.AutoField(primary_key=True, serialize=False)),
                ('mech_insp_desc', models.TextField(blank=True, null=True, verbose_name='وصف الفحص الميكانيكي')),
                ('comp_scan_desc', models.TextField(blank=True, null=True, verbose_name='وصف فحص الكمبيوتر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairshop_data', to='cars.cars', verbose_name='السيارة')),
            ],
            options={
                'verbose_name': 'بيانات الورشة',
                'verbose_name_plural': 'بيانات الورش',
                'db_table': 'repairshops',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['car', 'created_at'], name='repairshops_car_id_048823_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('overall_ai_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='التقييم الرقمي الشامل')),
                ('accident_severity_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='شدة الحادث')),
                ('risk_assessment_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات تحليل المخاطر (Charts JSON)')),
                ('car_snapshot', models.JSONField(blank=True, null=True, verbose_name='نسخة بيانات السيارة وقت التقرير')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='ملخص التقرير')),
                ('detailed_report', models.TextField(blank=True, null=True, verbose_name='التقرير المفصل')),
                ('ai_recommendations', models.TextField(blank=True, null=True, verbose_name='توصيات النظام الذكي')),
                ('total_images_count', models.PositiveIntegerField(default=0)),
                ('total_accidents_count', models.PositiveIntegerField(default=0)),
                ('avg_user_rating', models.FloatField(blank=True, null=True, verbose_name='متوسط تقييم المستخدمين')),
                ('has_mechanical_inspection', models.BooleanField(default=False, verbose_name='يوجد فحص ورشة')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تقرير موثق')),
                ('is_public', models.BooleanField(default=True, verbose_name='عام للجميع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='cars.cars', verbose_name='السيارة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير شامل',
                'verbose_name_plural': 'التقارير الشاملة',
                'db_table': 'Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_uuid'], name='Reports_report__93ca9e_idx'), models.Index(fields=['car'], name='Reports_car_id_f069e5_idx')],
            },
        ),
    ]
