# Generated by Django 6.0.3 on 2026-04-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentimage',
            name='accident_image',
            field=models.ImageField(blank=True, null=True, upload_to='accidents/', verbose_name='صورة الحادث'),
        ),
        migrations.AlterField(
            model_name='imagecar',
            name='img_car',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='صورة السيارة'),
        ),
    ]
