# Generated by Django 6.0.1 on 2026-04-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_accidentimage_accident_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentimage',
            name='accident_image',
            field=models.BinaryField(blank=True, null=True, verbose_name='صورة الحادث (تخزين في قاعدة البيانات)'),
        ),
        migrations.AlterField(
            model_name='imagecar',
            name='img_car',
            field=models.BinaryField(blank=True, null=True, verbose_name='صورة السيارة (تخزين في قاعدة البيانات)'),
        ),
    ]
