# Generated by Django 6.0.1 on 2026-04-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_accidentimage_accident_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecar',
            name='img_car',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='رابط صورة السيارة'),
        ),
        migrations.AlterField(
            model_name='accidentimage',
            name='accident_image',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='رابط صورة الحادث'),
        ),
    ]
