# Generated by Django 6.0.1 on 2026-04-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_imagecar_accidentimage_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentimage',
            name='accident_image',
            field=models.BinaryField(blank=True, null=True, verbose_name='صورة الحادث (تخزين في قاعدة البيانات)'),
        ),
    ]
