# Generated by Django 6.0.3 on 2026-04-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_accidentimage_accident_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecar',
            name='img_car',
            field=models.BinaryField(blank=True, null=True, verbose_name='صورة السيارة (تخزين في قاعدة البيانات)'),
        ),
    ]
