# Generated by Django 6.0.1 on 2026-05-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_imagecar_img_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentimage',
            name='accident_image',
            field=models.TextField(blank=True, null=True, verbose_name='رابط صورة الحادث (Data URL)'),
        ),
        migrations.AlterField(
            model_name='imagecar',
            name='img_car',
            field=models.TextField(blank=True, null=True, verbose_name='رابط صورة السيارة (Data URL)'),
        ),
    ]
