# Generated by Django 6.0.4 on 2026-05-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_accidentimage_accident_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='engine_size',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='ai_recommendations',
        ),
        migrations.AlterField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'بنزين'), ('diesel', 'ديزل'), ('electric', 'كهربائي'), ('hybrid', 'هجين'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الوقود'),
        ),
    ]
