# Generated by Django 6.0.4 on 2026-05-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_cars_engine_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='summary',
        ),
    ]
