# Generated by Django 6.0.1 on 2026-05-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_reports_has_mechanical_inspection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='has_mechanical_inspection',
        ),
    ]
