# Generated by Django 6.0.1 on 2026-05-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_reports_has_mechanical_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='القيمة المحسوبة بعد تطبيق الخصومات', max_digits=12, null=True, verbose_name='القيمة التقديرية الحالية'),
        ),
        migrations.AddField(
            model_name='cars',
            name='market_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='السعر الافتراضي للسيارة وهي بحالة ممتازة', max_digits=12, null=True, verbose_name='السعر الأساسي للسوق'),
        ),
    ]
