# Generated by Django 6.0.1 on 2026-05-07 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_cars_estimated_value_cars_market_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='estimated_value',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='market_base_price',
        ),
    ]
